CREATE TABLE AUTHORS( 
   ID INT AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR(20) NOT NULL,
   SURNAME VARCHAR(20) NOT NULL,
   PATRONYMIC VARCHAR(20) NOT NULL 
);

CREATE SEQUENCE "AUTHORS_SQ"
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 1 
START WITH 1
NOCACHE 
NOCYCLE;

ALTER TABLE AUTHORS ADD CONSTRAINT AUTHOR_UNIQUE UNIQUE(NAME, SURNAME, PATRONYMIC);


CREATE TABLE BOOKS( 
   ID INT AUTO_INCREMENT PRIMARY KEY,
   TITLE VARCHAR(50) NOT NULL,
   DATE_OF_PUBLICATION DATE NOT NULL,
   NUMBER_OF_COPIES INT NOT NULL
);

ALTER TABLE BOOKS ADD CONSTRAINT NUMBER_OF_COPIES_ABOVE_ZERO CHECK(NUMBER_OF_COPIES > -1);


CREATE SEQUENCE "BOOKS_SQ"
MINVALUE 1
MAXVALUE 999999999
INCREMENT BY 1
START WITH 1
NOCACHE
NOCYCLE;

ALTER TABLE BOOKS ADD CONSTRAINT BOOK_UNIQUE UNIQUE(TITLE ,DATE_OF_PUBLICATION);


CREATE TABLE BOOK_AUTHOR_LINKS(
   BOOK_ID INT NOT NULL,
   AUTHOR_ID INT NOT NULL
);

ALTER TABLE BOOK_AUTHOR_LINKS ADD PRIMARY KEY (BOOK_ID, AUTHOR_ID);
ALTER TABLE BOOK_AUTHOR_LINKS ADD CONSTRAINT LINKS_FOREIGN_KEY_AUTHOR FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(ID);
ALTER TABLE BOOK_AUTHOR_LINKS ADD CONSTRAINT LINKS_FOREIGN_KEY_BOOK FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(ID);


CREATE TABLE READERS( 
   ID INT AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR(20) NOT NULL,
   SURNAME VARCHAR(20) NOT NULL,
   PATRONYMIC VARCHAR(20) NOT NULL,
   SEX VARCHAR(1) NOT NULL,
   BIRTHDAY DATE NOT NULL
);

CREATE SEQUENCE "READERS_SQ" 
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 1 
START WITH 1
NOCACHE 
NOCYCLE;

ALTER TABLE READERS ADD CONSTRAINT READER_UNIQUE UNIQUE(NAME, SURNAME, PATRONYMIC, BIRTHDAY);
ALTER TABLE READERS ADD CONSTRAINT SEX_CHECK CHECK (SEX IN ('M','F'));


CREATE TABLE BOOKS_ISSUE_JN( 
   READER_ID INT NOT NULL,
   BOOK_ID INT NOT NULL,
   DATE_OF_ISSUE DATETIME NOT NULL,
   DATE_OF_RETURN DATETIME
);

ALTER TABLE BOOKS_ISSUE_JN ADD PRIMARY KEY (READER_ID , BOOK_ID , DATE_OF_ISSUE);
ALTER TABLE BOOKS_ISSUE_JN ADD CONSTRAINT JN_FOREIGN_KEY_READER FOREIGN KEY(READER_ID) REFERENCES READERS(ID);
ALTER TABLE BOOKS_ISSUE_JN ADD CONSTRAINT JN_FOREIGN_KEY_BOOK FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(ID);







SELECT * FROM BOOKS;
SELECT * FROM BOOK_AUTHOR_LINKS ;
SELECT * FROM AUTHORS ;
SELECT * FROM BOOKS_ISSUE_JN ;
SELECT * FROM READERS ;
